name: Website Publish

on:
  push:
    branches:
      - main
      - stage-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1.8.3
        with:
          base-url-path: "https://www.julian-lemmerich.de/"
          include-pdfs: true
      - name: Upload to Webhost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: www184.your-server.de
          username: ${{ secrets.HETZNER_FTP_USR }}
          password: ${{ secrets.HETZNER_FTP_PWD }}
          protocol: "ftps"
          local-dir: "./"
          server-dir: "./www/"
          overwrite: true
